### ISSUE TITLE
Does Opensearch operator version 2.4.0 supports the Opensearch version 2.10.0?

### ISSUE THREAD

**Issue by Gokul-Radhakrishnan** [Opster/opensearch-k8s-operator#635] opened 2023-10-12 09:51 UTC
I don't see the compatibility table updated with operator version 2.4.0
![image](https://github.com/Opster/opensearch-k8s-operator/assets/38651133/a4265d3e-5898-492c-85e9-0fae28be85b9)

**Comment by swoehrl-mw** [comment] 2023-10-12 14:06
Duplicate of discussion #630

**Closed by swoehrl-mw** 2023-10-12 14:06 UTC
