### ISSUE TITLE
 Need repository-s3 during bootstrap for remote-backed storage

### ISSUE THREAD

**Issue by kuro96al** [Opster/opensearch-k8s-operator#639] opened 2023-10-13 03:48 UTC
Hello,

I'm trying to utilize remote-backed storage. However, it seems that during the bootstrap process, the repository-s3 plugin is required. As of now, plugins cannot be used during bootstrap, rendering the use of remote-backed storage impossible.

Is there a workaround for this or any plans to support plugins like repository-s3 during bootstrap? This capability would greatly enhance our workflow.

Thank you!

**Comment by kuro96al** [comment] 2023-10-13 03:49
Summary:
Remote-backed storage in OpenSearch allows for the automatic creation of backups of all index transactions, sending them to remote storage. This feature requires segment replication to be activated. The main mechanism involves indexing write requests to Lucene on the primary shard only, then uploading the corresponding translog to a remote store. This storage method must be enabled during the cluster bootstrapping process, and once set, cannot be toggled on/off. The communication with the configured remote cluster is facilitated through the Repository plugin interface, and this is compatible with various storage solutions like Amazon S3​[1](https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/remote-store/index/)​.

Analysis:
Given your initial concern about the necessity of the repository-s3 during bootstrapping, it's clear from the documentation that during the bootstrapping process, the remote-backed repositories listed in opensearch.yml are automatically registered. This means the repository configurations, such as those for S3, are vital at this stage. The inability to use plugins like repository-s3 during bootstrapping poses a challenge for those wanting to use remote-backed storage, especially if they are looking to utilize solutions like Amazon S3. This could be a significant limitation for users who rely on S3 or similar services for their storage solutions.

**Comment by swoehrl-mw** [comment] 2023-10-13 10:58
Hi @kuro96al. Your issue looks a lot like the one from #430. Does the workaround described there work for you?

**Comment by kuro96al** [comment] 2023-10-16 03:55
It is a separate issue.
In order to utilize remote-backed storage, it is necessary to configure S3 during bootstrap. Therefore, it is necessary for repository-s3 to be referable during bootstrap.

Remote-backed storage is a cluster level setting. It can only be enabled when bootstrapping to the cluster.
https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/remote-store/index/

**Comment by kuro96al** [comment] 2023-10-16 04:00
If the plugin is not referenced during bootstrap, the following error will occur during node startup:
```
[2023-10-12T19:08:30,565][INFO ][o.o.c.c.JoinHelper       ] [opensearch-test-nodes-0] failed to join {opensearch-test-bootstrap-0}{JS8nlEHCT2aOwmW1y0fC-g}{mXL7GcmDTHazlvq99Estyg}{opensearch-test-bootstrap-0}{10.233.89.222:9300}{m}{shard_indexing_pressure_enabled=true} with JoinRequest{sourceNode={opensearch-test-nodes-0}{8Y82plKwQZuSXp32J5bC7g}{8D66PwhcTpKjVzzJkp3PFw}{opensearch-test-nodes-0}{10.233.89.215:9300}{dim}{remote_store.repository.my-repo.settings.region=dev, remote_store.repository.my-repo.type=s3, remote_store.repository.my-repo.settings.base_path=store, remote_store.state.repository=my-repo, remote_store.repository.my-repo.settings.bucket=abyss2-test-opensearch-store, shard_indexing_pressure_enabled=true, remote_store.segment.repository=my-repo, remote_store.translog.repository=my-repo}, minimumTerm=1, optionalJoin=Optional[Join{term=1, lastAcceptedTerm=0, lastAcceptedVersion=0, sourceNode={opensearch-test-nodes-0}{8Y82plKwQZuSXp32J5bC7g}{8D66PwhcTpKjVzzJkp3PFw}{opensearch-test-nodes-0}{10.233.89.215:9300}{dim}{remote_store.repository.my-repo.settings.region=dev, remote_store.repository.my-repo.type=s3, remote_store.repository.my-repo.settings.base_path=store, remote_store.state.repository=my-repo, remote_store.repository.my-repo.settings.bucket=abyss2-test-opensearch-store, shard_indexing_pressure_enabled=true, remote_store.segment.repository=my-repo, remote_store.translog.repository=my-repo}, targetNode={opensearch-test-bootstrap-0}{JS8nlEHCT2aOwmW1y0fC-g}{mXL7GcmDTHazlvq99Estyg}{opensearch-test-bootstrap-0}{10.233.89.222:9300}{m}{shard_indexing_pressure_enabled=true}}]}
org.opensearch.transport.RemoteTransportException: [opensearch-test-bootstrap-0][10.233.89.222:9300][internal:cluster/coordination/join]
Caused by: java.lang.IllegalStateException: a remote store node [{opensearch-test-nodes-0}{8Y82plKwQZuSXp32J5bC7g}{8D66PwhcTpKjVzzJkp3PFw}{opensearch-test-nodes-0}{10.233.89.215:9300}{dim}{remote_store.repository.my-repo.settings.region=dev, remote_store.repository.my-repo.type=s3, remote_store.repository.my-repo.settings.base_path=store, remote_store.state.repository=my-repo, remote_store.repository.my-repo.settings.bucket=abyss2-test-opensearch-store, shard_indexing_pressure_enabled=true, remote_store.segment.repository=my-repo, remote_store.translog.repository=my-repo}] is trying to join a non remote store cluster
        at org.opensearch.cluster.coordination.JoinTaskExecutor.ensureRemoteStoreNodesCompatibility(JoinTaskExecutor.java:579) ~[opensearch-2.10.0.jar:2.10.0]
        at org.opensearch.cluster.coordination.JoinTaskExecutor.ensureNodesCompatibility(JoinTaskExecutor.java:507) ~[opensearch-2.10.0.jar:2.10.0]
        at org.opensearch.cluster.coordination.JoinTaskExecutor.ensureNodesCompatibility(JoinTaskExecutor.java:470) ~[opensearch-2.10.0.jar:2.10.0]
        at org.opensearch.cluster.coordination.JoinTaskExecutor.lambda$addBuiltInJoinValidators$3(JoinTaskExecutor.java:598) ~[opensearch-2.10.0.jar:2.10.0]
        at org.opensearch.cluster.coordination.Coordinator.lambda$handleJoinRequest$6(Coordinator.java:606) ~[opensearch-2.10.0.jar:2.10.0]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
        at org.opensearch.cluster.coordination.Coordinator.lambda$handleJoinRequest$7(Coordinator.java:606) ~[opensearch-2.10.0.jar:2.10.0]
        at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) ~[opensearch-core-2.10.0.jar:2.10.0]
        at org.opensearch.transport.ClusterConnectionManager.connectToNode(ClusterConnectionManager.java:138) ~[opensearch-2.10.0.jar:2.10.0]
        at org.opensearch.transport.TransportService.connectToNode(TransportService.java:493) ~[opensearch-2.10.0.jar:2.10.0]
        at org.opensearch.transport.TransportService.connectToNode(TransportService.java:473) ~[opensearch-2.10.0.jar:2.10.0]
        at org.opensearch.cluster.coordination.Coordinator.handleJoinRequest(Coordinator.java:602) ~[opensearch-2.10.0.jar:2.10.0]
        at org.opensearch.cluster.coordination.JoinHelper.lambda$new$1(JoinHelper.java:209) ~[opensearch-2.10.0.jar:2.10.0]
        at org.opensearch.security.ssl.transport.SecuritySSLRequestHandler.messageReceivedDecorate(SecuritySSLRequestHandler.java:215) ~[?:?]
        at org.opensearch.security.transport.SecurityRequestHandler.messageReceivedDecorate(SecurityRequestHandler.java:315) ~[?:?]
        at org.opensearch.security.ssl.transport.SecuritySSLRequestHandler.messageReceived(SecuritySSLRequestHandler.java:163) ~[?:?]
        at org.opensearch.security.OpenSearchSecurityPlugin$7$1.messageReceived(OpenSearchSecurityPlugin.java:763) ~[?:?]
        at org.opensearch.indexmanagement.rollup.interceptor.RollupInterceptor$interceptHandler$1.messageReceived(RollupInterceptor.kt:113) ~[?:?]
        at org.opensearch.performanceanalyzer.transport.PerformanceAnalyzerTransportRequestHandler.messageReceived(PerformanceAnalyzerTransportRequestHandler.java:43) ~[?:?]
        at org.opensearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:106) ~[opensearch-2.10.0.jar:2.10.0]
        at org.opensearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:454) ~[opensearch-2.10.0.jar:2.10.0]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908) ~[opensearch-2.10.0.jar:2.10.0]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.10.0.jar:2.10.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
        ```

**Comment by kuro96al** [comment] 2023-10-16 04:02
The most important part of the error is as follows, and occurs because the S3 configuration was not included during bootstrap:

is trying to join a non remote store cluster

**Comment by kuro96al** [comment] 2023-10-16 04:04
The following setting(opensearch.yml) should be passed specifically:
```
  bootstrap:
    jvm: '-Xmx2048M -Xms2048M  -Dhttp.proxyHost=pwg01-8080.yahoo-net.jp -Dhttp.proxyPort=8080 -Dhttps.proxyHost=pwg01-8080.yahoo-net.jp -Dhttps.proxyPort=8080 -Dhttp.nonProxyHosts="localhost|*.nonproxy.com|127.0.0.1|*.corp.yahoo.co.jp|*.dev.yahoo.co.jp|*.icos-d.yahoo.co.jp"'
    additionalConfig:
      cluster.indices.replication.strategy: 'SEGMENT'
      node.attr.remote_store.segment.repository: my-repo
      node.attr.remote_store.translog.repository: my-repo
      node.attr.remote_store.state.repository: my-repo
      node.attr.remote_store.repository.my-repo.type: s3
      node.attr.remote_store.repository.my-repo.settings.bucket: abyss2-test-opensearch-store
      node.attr.remote_store.repository.my-repo.settings.base_path: store
      node.attr.remote_store.repository.my-repo.settings.region: "dev"
```

**Comment by swoehrl-mw** [comment] 2023-11-28 14:01
Duplicate of #430 . Installing plugins in the bootstrap pod is tracked there. Closing this issue.

**Closed by swoehrl-mw** 2023-11-28 14:01 UTC
Labels: enhancement
