### ISSUE TITLE
Unable to customize opensearch dashboard deployment

### ISSUE THREAD

**Issue by samuelruiz2020** [Opster/opensearch-k8s-operator#552] opened 2023-07-03 15:49 UTC
**Describe the bug**
Hello, I don´t find a way to make changes to  opensearch dashboard deployment . First of all,  I made some configuration changes for stsfulset resources and  the process I followed worked, but  is not working on deployments for opensearch dashboards. And evidently I thing the reason is the operator.  

Each time a try to patch the dashboard deployment , changes do not take effect. If a run  _`kubectl patch deployment -n cne-infra my-cluster-dashboards --patch-file  my-cluster-dashboards.yaml_ it` creates a new pod with the change but retained the old pods with image pull back off error. 

**To Reproduce**
1. kubectl scale deployment opensearch-operator-controller-manager --replicas=0 -n occne-infra
2. kubectl scale deployment my-cluster-dashboards  --replicas=0 -n cne-infra
3. kubectl get -o yaml -n cne-infra deployments.apps my-cluster-dashboards >> my-cluster-dashboards.yaml
4. kubectl delete deploy  my-cluster-dashboards -n cne-infra
5. Modify  my-cluster-dashboards.yaml  (in this case i test image )
6. kubectl apply -f my-cluster-dashboards.yaml
7. kubectl scale deployment my-cluster-dashboards  --replicas=2 -n cne-infra
8. kubectl scale deployment opensearch-operator-controller-manager --replicas=1 -n cne-infra

**Expected behavior**
Pods / Deployments and replicas in healthy state. Pods Running.

**OpenSearch Version**
2.3.0

**Dashboards Version**
1.3.0

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

`kubectl get all -A | grep dash

cne-infra     pod/my-cluster-dashboards-cb7d645fb-2z2bc                         0/1     ImagePullBackOff    0                  26m
cne-infra     pod/my-cluster-dashboards-cb7d645fb-6kl78                         0/1     ImagePullBackOff    0                  26m
cne-infra    service/my-cluster-dashboards                                    ClusterIP      10.233.28.189   <none>          5601/TCP                                          13h
cne-infra    deployment.apps/my-cluster-dashboards                      0/2     2            0           7h48m
cne-infra    replicaset.apps/my-cluster-dashboards-5c77c8d8bc                      0         0         0       7h48m
cne-infra    replicaset.apps/my-cluster-dashboards-cb7d645fb                       2         2         0       7h46m
`

**Host/Environment (please complete the following information):**
 
NAME="Oracle Linux Server"
VERSION="8.8"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.8"

**Additional context**

**Comment by swoehrl-mw** [comment] 2023-07-04 06:15
Hi @samuelruiz2020. You should never make direct changes to the statefulsets or deployments managed by the operator, that is not supported and any changes will get overwritten by the operator during reconciliation. Any changes you want to make to the dashboards deployment you must make in the `OpenSearchCluster` spec and let the operatator apply it.
If there are things you want to configure but the CRD has no option for it, feel free to raise a feature request.

**Comment by samuelruiz2020** [comment] 2023-07-07 14:09
@swoehrl-mw  Hi, thank u ! I knew how to implemeted changes. Now there is one thing i need to make , how can i do to make changes to opensearch service? i need to make my svc accesible externally and i am using Loadbalancer, so i need to change from ClusterIP to LoadBalancer and more settings .    Looking info It's tell me that i need to add a path on the opensearch operator , 

something like could be 
`apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
#...
spec:
  dashboards:
  additionalConfig:
    # path to my svc 
    /opensearch-dashboards
    "`

I appreciate if you can explain me  please a little more.

What am i doing is to test on a pre-production env how to install a opensearch cluster using the opensearch operator. 
Curretly the clusters work whithout opensearch operator.

**Comment by samuelruiz2020** [comment] 2023-07-07 14:16
What I observe is in the clusters that work and in which the components are managed through helm, the opensearh dashboard deploy has port 80 configured, I try to modify it from the opensearh-cluster.yaml file with the additionalConfig and it does not accept the change. I already know by default the opensarch dashboard is bind 5601, but then what is the flow that I must follow so that this is operational and functional?

**Comment by swoehrl-mw** [comment] 2023-07-27 11:08
Closing as this is not a bug.

**Closed by swoehrl-mw** 2023-07-27 11:08 UTC
Labels: waiting-for-reporter, triaged
