### ISSUE TITLE
Feature: Support ISM configs

### ISSUE THREAD

**Issue by IshaGirdhar** [Opster/opensearch-k8s-operator#494] opened 2023-04-19 13:02 UTC
Today ISM policies can only be managed by normal OpenSearch APIs and not through the operator. The feature request is to allow users to specify their ISM configs that will be managed by the Operator. Though I already see that in the roadmap but I didn't see any issue opened for that. I will be happy to contribute and have design discussions around it.

We already have a JSON schema for the configs https://github.com/opensearch-project/index-management/blob/main/src/main/resources/mappings/opendistro-ism-config.json, thinking if we can dynamically convert this into OpenAPI schema and generate the CRD.

**Comment by AndersBennedsgaard** [comment] 2023-05-09 09:51
Duplicate of #435

**Closed as completed** 2023-05-10 13:30 UTC
Labels: enhancement
